site_name: KFS
Nav:
  Home: 
    - index.md
  About: 
    - about.md
  Core:
    - core.md
  Locking:
    - locking.md
  Signals:
    - Signals.md
  LibC:
    - Signals.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - zig
    - bash
  features:
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - codehilite
  - toc:
      permalink: true
